version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5002:5002"
    depends_on:
      - ambassador
    restart: always  # Ensures the service restarts if it fails

  ambassador:
    build: ./ambassador_proxy
    ports:
      - "5000:5000"
    depends_on:
      - weather_service
      - sidecar
    restart: always

  weather_service:
    build: ./weather_service
    ports:
      - "5001:5001"
    restart: always

  sidecar:
    build: ./sidecar_service
    ports:
      - "5003:5003"
    volumes:
      - ./sidecar_service/logs:/logs  # Persist logs outside the container
    restart: always
